---
title: Datasets
bibliography: references.bib
---

# Overview

This documents describes the datasets used in
@stroeve_multi-sensor_2021.  Three datasets are used:

- Sea Ice Concentrations from Nimbus-7 SMMR and DMSP SSM/I-SSMIS
  Passive Microwave Data, Version 2 (@digirolamo_ice_concentration_2022).  [Link](https://nsidc.org/data/g02135/versions/3)
- Surface albedo, incident shortwave radiation and surface temperature
  from the Extended AVHRR Polar Pathfinder (APP-x), Version 2
  (@key_noaa_2016).  [User Guide](https://www.ncei.noaa.gov/pub/data/sds/cdr/CDRs/AVHRR_Extended_Polar_Pathfinder/AlgorithmDescription_01B-24b.pdf)
- Snow Depth from Lagrangian Snow Distributions for Sea-Ice
  Applications, Version 1 ([NSIDC-0758](https://nsidc.org/data/nsidc-0758/versions/1#anchor-2)) (@liston_glen_lagrangian_2020)
- Sea Ice Thickness Jack Landy's 


[Results](ftp://sidads.colorado.edu/pub/projects/SIPN/Ecolight)

# Processing

Daily grids of sea ice concentration, ice thickness, snow depth, along
with surface albedo, daily incoming solar radiation at the surface and
surface temperature, are reprojected and resampled to a common grid;
the 25 km EASE Grid (see below for projection and grid definition).

Unfortunately, not all datasets contain sufficient information to
reproject and regrid.  Projection and grid definitions for each
dataset are included below for reference.

| Dataset  | Proj4 String  | Grid |
|--------|--------|-------|
| Sea Ice Concentrations from Nimbus-7 SMMR and DMSP SSM/I-SSMIS
|Passive Microwave Data, Version 2  | +proj=stere +lat_0=90 +lat_ts=70
|+lon_0=-45 +k=1 +x_0=0 +y_0=0 +a=6378273 +b=6356889.449 +units=m
|+no_defs  | 304x348 |
| Lagrangian Snow Distributions for Sea-Ice Applications, Version 1 | +proj=laea +lat_0=90 +lon_0=0 +x_0=0 +y_0=0
+a=6371228 +b=6371228 +units=m +no_defs | 721x721 |
| Extended AVHRR Polar Pathfinder (APP-x) | +proj=laea +lat_0=90 +lon_0=0 +x_0=0 +y_0=0
+a=6371228 +b=6371228 +units=m +no_defs | 361x361 |

: Datasets {tbl-colwidths="[50,25,25]"}

| Name | Proj4 String | URL |
|------|--------------|-----|
|NSIDC Sea Ice Polar Stereographic North | +proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +k=1 +x_0=0 +y_0=0 +a=6378273 +b=6356889.449 +units=m +no_defs | https://nsidc.org/data/user-resources/help-center/guide-nsidcs-polar-stereographic-projection |

: Projections {tbl-colwidths="[25,50,25]"}
